"""initial_schema_v2

Revision ID: 65065b8dc1c5
Revises: 
Create Date: 2026-04-18 23:03:43.349979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '65065b8dc1c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Habilitar PostGIS si no está presente
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_servicio',
    sa.Column('id_categoria', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('taller',
    sa.Column('id_taller', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('nit', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_taller')
    )
    op.create_index(op.f('ix_taller_nit'), 'taller', ['nit'], unique=True)
    op.create_table('tallercategoria_servicio',
    sa.Column('id_taller_cat', sa.UUID(), nullable=False),
    sa.Column('id_taller', sa.UUID(), nullable=False),
    sa.Column('id_categoria', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria_servicio.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.PrimaryKeyConstraint('id_taller_cat')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_rol', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_table('administradortaller',
    sa.Column('id_admin_taller', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_taller', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_admin_taller')
    )
    op.create_table('bitacora',
    sa.Column('id_bitacora', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('accion', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_bitacora')
    )
    op.create_table('notificacion',
    sa.Column('id_notificacion', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('tipo_notificacion', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_table('tecnico',
    sa.Column('id_tecnico', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_taller', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_tecnico')
    )
    op.create_table('vehiculo',
    sa.Column('id_vehiculo', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_vehiculo')
    )
    op.create_index(op.f('ix_vehiculo_matricula'), 'vehiculo', ['matricula'], unique=True)
    op.create_table('disponibilidad_tecnico',
    sa.Column('id_disponibilidad', sa.UUID(), nullable=False),
    sa.Column('id_tecnico', sa.UUID(), nullable=False),
    sa.Column('dia', sa.String(length=20), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('hora_ini', sa.Time(), nullable=False),
    sa.Column('disponibilidad', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_tecnico'], ['tecnico.id_tecnico'], ),
    sa.PrimaryKeyConstraint('id_disponibilidad')
    )
    op.create_table('incidente',
    sa.Column('id_incidente', sa.UUID(), nullable=False),
    sa.Column('id_vehiculo', sa.UUID(), nullable=False),
    sa.Column('id_taller', sa.UUID(), nullable=True),
    sa.Column('ubicacion_emergencia', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado_incidente', sa.String(length=50), nullable=False),
    sa.Column('prioridad_incidente', sa.String(length=20), nullable=False),
    sa.Column('transcripcion_audio', sa.Text(), nullable=True),
    sa.Column('resumen_ia', sa.Text(), nullable=True),
    sa.Column('analisis_consolidado', sa.Text(), nullable=True),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculo.id_vehiculo'], ),
    sa.PrimaryKeyConstraint('id_incidente')
    )
    op.create_table('asignacion_incidente',
    sa.Column('id_asignacion', sa.UUID(), nullable=False),
    sa.Column('id_incidente', sa.UUID(), nullable=False),
    sa.Column('id_tecnico', sa.UUID(), nullable=False),
    sa.Column('estado_asignacion', sa.String(length=50), nullable=False),
    sa.Column('score_asignacion', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('distancia_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id_incidente'], ),
    sa.ForeignKeyConstraint(['id_tecnico'], ['tecnico.id_tecnico'], ),
    sa.PrimaryKeyConstraint('id_asignacion')
    )
    op.create_table('evidencia_incidente',
    sa.Column('id_evidencia', sa.UUID(), nullable=False),
    sa.Column('id_incidente', sa.UUID(), nullable=False),
    sa.Column('evidencia_tipo', sa.String(length=50), nullable=False),
    sa.Column('archivo_url', sa.String(length=500), nullable=False),
    sa.Column('transcripcion', sa.Text(), nullable=True),
    sa.Column('confianza_deteccion', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('tipo_de_combustible', sa.String(length=50), nullable=True),
    sa.Column('analisis_imagen', sa.Text(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id_incidente'], ),
    sa.PrimaryKeyConstraint('id_evidencia')
    )
    op.create_table('historial_incidente',
    sa.Column('id_historial', sa.UUID(), nullable=False),
    sa.Column('id_incidente', sa.UUID(), nullable=False),
    sa.Column('incidente_estado_anterior', sa.String(length=50), nullable=True),
    sa.Column('incidente_estado_nuevo', sa.String(length=50), nullable=False),
    sa.Column('historial_actor', sa.String(length=150), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id_incidente'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_table('pago',
    sa.Column('id_pago', sa.UUID(), nullable=False),
    sa.Column('id_incidente', sa.UUID(), nullable=False),
    sa.Column('id_taller', sa.UUID(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_comision', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado_pago', sa.String(length=50), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id_incidente'], ),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('historial_incidente')
    op.drop_table('evidencia_incidente')
    op.drop_table('asignacion_incidente')
    op.drop_table('incidente')
    op.drop_table('disponibilidad_tecnico')
    op.drop_index(op.f('ix_vehiculo_matricula'), table_name='vehiculo')
    op.drop_table('vehiculo')
    op.drop_table('tecnico')
    op.drop_table('notificacion')
    op.drop_table('bitacora')
    op.drop_table('administradortaller')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('tallercategoria_servicio')
    op.drop_index(op.f('ix_taller_nit'), table_name='taller')
    op.drop_table('taller')
    op.drop_table('roles')
    op.drop_table('categoria_servicio')
    # ### end Alembic commands ###
